[package]
name = "catimg"
version = "0.1.0"
edition = "2024"
authors = ["jiwonz <me@jiwonz.kr>"]
description = "Cat and Preview your images directly in terminal using sixel"
repository = "https://github.com/jiwonz/catimg"
keywords = ["cat", "preview", "image", "terminal", "sixel"]
license = "MIT"
readme = "README.md"

[badges]
github = { repository = "https://github.com/jiwonz/catimg" }

[[bin]]
name = "catimg"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }
icy_sixel = "0.1.3"
image = "0.25.6"
